---
title: "Significant Metabolites Analysis"
author: "Jeremy Ash"
output:
  pdf_document:
    toc: true
    number_sections: true
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
# You will need to replace with the path to the data directory on your machine
knitr::opts_knit$set(root.dir = 'data/')
library(car)
library(ChemmineR)
library(lme4)
library(perm)
```

# Training Set

```{r cars}
rm(list = ls())
sdfset <- read.SDFset("common_test_training_molecule-v2.sdf")

# test for significance with only compounds that have chemical structures
f1 <- read.delim(file = "sample_factors_training.txt", header = T, row.names = 1)
f2 <- read.csv(file = "sample_metabolites_training_excol_fix.csv", header = T, row.names = 1)

# removing the observations with no factor levels
f1 <- na.omit(f1)
rownames(f1) <- f1$Sample.name

# create patient identifier column
f1$Subject_name <- gsub(" Plasma| Serum", "", f1$Subject_name, perl = T)

f1 <- f1[, -2]
colnames(f1) <- c("Patient","Organ", "Health_State", "Smoking_Status", "Gender")
head(f1)

f2 <- t(f2)

# save this processed data frame so you can try different processing
before.process <- f2

# save.image("training_set.rda")

# two metabolites with missing values, use imputation, take half the minimum
# of that metabolite's value
# also, perform log base 2 transformation.  I cannot for the life of me
# figure out how they did their normalization
# lactic acid had some zero values? impute those too
f2 <- apply(f2, 2, function(x) {
  x[is.na(x)] <- .5*min(na.omit(x))
  x[x == 0] <- .5*min(na.omit(x[x != 0]))
  x
})

# # not necessary to do total quantity normalization
# # pvalues dont change see below
for(i in 1:nrow(f2)){
  f2[i, ] <- f2[i, ]/sum(f2[i, ])
}

# log transformation
f2 <- log(f2, base = 2)

summary(f2[, 1:6])

# fix compound names so that they are the same
# format as the file provided by Melaine
ids <- sdfid(sdfset)
ids.new <- gsub(" |,","_",ids, perl = T)
colnames(f2) <- gsub(" |,","_", colnames(f2), perl = T)

# 130 compounds provided
sum(ids.new %in% colnames(f2))
dim(f2)

f2 <- f2[, colnames(f2) %in% ids.new]
orig.mets <- colnames(f2)[colnames(f2) %in% ids.new]

rownames(f2) <- sub("X", "", row.names(f2))
d <- merge(f1, f2, by.x= "row.names", by.y = "row.names")

d$Organ <- factor(d$Organ)

#replacing mispelled adenocarcinoma and "Adenosquamous" with Adenocarcinoma
d$Health_State <- gsub("Adenocarcnoma|Adenosquamous", "Adenocarcinoma", d$Health_State)
row.names(d) <- d$Row.names
d$Row.names <- NULL
save.image("training_set_tq_nonormalize.rda")
```

## Patient characteristic table

```{r}
table(d$Organ, d$Health_State)
table(d$Organ, d$Smoking_Status)
table(d$Organ, d$Smoking_Status, d$Health_State)
table(d$Organ, d$Gender)
table(d$Organ, d$Gender, d$Health_State)
```

## T-Tests for Significant differences

```{r pressure}

vars = colnames(d)[6:ncol(d)]
varNum <- length(vars)
pkimodels <- vector("list", (varNum))
pkimodelspvals <- vector("list", (varNum))
pkimodelseffect <- vector("list", (varNum))
pkimodelsmean <- vector("list", (varNum))

#----controling for all factors, including organ

for (i in 1:(varNum)){
  lmfit <- lm(d[,i+5]~ Organ + Health_State + Smoking_Status + Gender, data = d)
  pkimodels[[i]] <- lmfit
  #pvalue for regressing each variable in df on AC50
  pkimodelspvals[[i]] <- Anova(lmfit, type = "III")$`Pr(>F)`[3]
  
  pkimodelseffect[[i]] <- log(mean(2^(d[d$Health_State == "Adenocarcinoma",i+5]))/mean(2^(d[d$Health_State == "Healthy",i+5])), base=2)
  # mins[[i]] <- min(d[,220])
}

pki_ps = unlist(pkimodelspvals)
pki_ps <- p.adjust(pki_ps, method = "BH")

pki_effect = unlist(pkimodelseffect)
plot(pki_effect, -log(pki_ps, base = 10))
log2FoldChange <- pki_effect

univariate_res_control = data.frame(variables = vars, pvalues = pki_ps, log2FoldChange = log2FoldChange)
univariate_res_control$significance <- univariate_res_control$pvalues < .05
sig_no_block <- univariate_res_control$pvalues < .05
write.csv(univariate_res_control, "significance_results/healthstate_anova_wsig_control_training.txt", row.names = F)

#-----Using patient as blocking factor

for (i in 1:(varNum)){
  lmfit <- lmer(d[,i+5]~ Organ + Health_State + Smoking_Status + Gender + (1|Patient), data = d)
  pkimodels[[i]] <- lmfit
  #pvalue for regressing each variable in df on AC50
  pkimodelspvals[[i]] <- Anova(lmfit, type = "III")$`Pr(>Chisq)`[3]
  
  pkimodelseffect[[i]] <- mean(2^(d[d$Health_State == "Adenocarcinoma",i+5]))/mean(2^(d[d$Health_State == "Healthy",i+5]))
  # mins[[i]] <- min(d[,220])
}

pki_effect = unlist(pkimodelseffect)
log2FoldChange <- pki_effect

pki_ps_raw = unlist(pkimodelspvals)
plot(log(pki_effect, base = 2), -log(pki_ps_raw, base = 10))
pki_ps_adj <- p.adjust(pki_ps_raw, method = "BH")
plot(log(pki_effect, base = 2), -log(pki_ps_adj, base = 10))

univariate_res_control = data.frame(variables = vars, pvalues = pki_ps_raw,
                                    adj_pvalues = pki_ps_adj,
                                    FoldChange = log2FoldChange)
univariate_res_control$significance_raw <- univariate_res_control$pvalues < .05
univariate_res_control$significance_adj <- univariate_res_control$adj_pvalues < .05
write.csv(univariate_res_control, "significance_results/healthstate_anova_wsig_control_training_block.txt", row.names = F)


#----only analyze the samples collected from Serum
d_serum <- d[d$Organ == "Serum", ]
#----controling for all factors
for (i in 1:(varNum)){
  lmfit <- lm(d_serum[,i+5]~ Health_State + Smoking_Status + Gender, data = d_serum)
  pkimodels[[i]] <- lmfit
  #pvalue for regressing each variable in df on AC50
  pkimodelspvals[[i]] <- Anova(lmfit, type = "III")$`Pr(>F)`[3]
  
  pkimodelseffect[[i]] <- 
    log(mean(2^(d_serum[d_serum$Health_State == "Adenocarcinoma",i+5]))/mean(2^(d_serum[d_serum$Health_State == "Healthy",i+5])), base=2)
  pkimodelsmean[[i]] <- mean(d_serum[d_serum$Health_State == "Adenocarcinoma",i+5])
}

pki_ps = unlist(pkimodelspvals)
pki_ps <- p.adjust(pki_ps, method = "BH")

pki_effect = unlist(pkimodelseffect)
plot(pki_effect, -log(pki_ps, base = 10))
log2FoldChange <- pki_effect
pkimodelsmean <- unlist(pkimodelsmean)

univariate_res_control = data.frame(variables = vars, pvalues = pki_ps,
                                    log2FoldChange = log2FoldChange, 
                                    pkimodelsmean = pkimodelsmean)
univariate_res_control$significance <- univariate_res_control$pvalues < .05

sum(univariate_res_control$significance)
write.csv(univariate_res_control, "significance_results/healthstate_anova_wsig_control_training_serum.txt", row.names = F)

#----only analyze the samples collected from plasma
d_plasma <- d[d$Organ == "Plasma", ]

#----controling for all factors
for (i in 1:(varNum)){
  lmfit <- lm(d_plasma[,i+5]~ Health_State + Smoking_Status + Gender, data = d_plasma)
  pkimodels[[i]] <- lmfit
  #pvalue for regressing each variable in df on AC50
  pkimodelspvals[[i]] <- Anova(lmfit, type = "III")$`Pr(>F)`[3]
  
  pkimodelseffect[[i]] <- 
    log(mean(2^(d_plasma[d_plasma$Health_State == "Adenocarcinoma",i+5]))/
          mean(2^(d_plasma[d_plasma$Health_State == "Healthy",i+5])), base=2)
  pkimodelsmean[[i]] <- mean(d_plasma[d_plasma$Health_State == "Adenocarcinoma",i+5])
  
}

pki_ps = unlist(pkimodelspvals)
pki_ps <- p.adjust(pki_ps, method = "BH")

pki_effect = unlist(pkimodelseffect)
plot(pki_effect, -log(pki_ps, base = 10))
log2FoldChange <- pki_effect
pkimodelsmean <- unlist(pkimodelsmean)

univariate_res_control = data.frame(variables = vars, pvalues = pki_ps,
                                    log2FoldChange = log2FoldChange, 
                                    pkimodelsmean = pkimodelsmean)
univariate_res_control$significance <- univariate_res_control$pvalues < .05
sum(univariate_res_control$significance)
write.csv(univariate_res_control, "significance_results/healthstate_anova_wsig_control_training_plasma.txt", row.names = F)

```

## Non-parameteric approach

```{r t-test_comp, cache=T}
#----only analyze the samples collected from Serum
d_serum <- d[d$Organ == "Serum", ]
#----controling for all factors
for (i in 1:(varNum)){
  lmfit <- lm(d_serum[,i+5]~ Smoking_Status + Gender, data = d_serum)
  pkimodelspvals[[i]] <-   permTS(lmfit$residuals ~ Health_State, data = d_serum,
                                  alternative="two.sided", method="exact.mc",
                                  control=permControl(nmc=10^5))$p.value
  # Switched to reporting FC instead of logFC here so that can get right input for volcano plot
  # on metabolomics workbench
  pkimodelseffect[[i]] <-
    mean(2^(d_serum[d_serum$Health_State == "Adenocarcinoma",i+5]))/mean(2^(d_serum[d_serum$Health_State == "Healthy",i+5]))
  pkimodelsmean[[i]] <- mean(d_plasma[d_plasma$Health_State == "Adenocarcinoma",i+5])
}

pki_effect = unlist(pkimodelseffect)
FoldChange <- pki_effect
pkimodelsmean <- unlist(pkimodelsmean)

pki_ps_raw = unlist(pkimodelspvals)
plot(log(pki_effect, base = 2), -log(pki_ps_raw, base = 10))
pki_ps_adj <- p.adjust(pki_ps_raw, method = "BH")
plot(log(pki_effect, base = 2), -log(pki_ps_adj, base = 10))

univariate_res_control = data.frame(variables = vars, pvalues = pki_ps_raw,
                                    adj_pvalues = pki_ps_adj,
                                    FoldChange = FoldChange,
                                    pkimodelsmean = pkimodelsmean)
univariate_res_control$significance_raw <- univariate_res_control$pvalues < .05
univariate_res_control$significance_adj <- univariate_res_control$adj_pvalues < .05
write.csv(univariate_res_control, "significance_results/healthstate_anova_wsig_control_training_serum_nonpara.txt", row.names = F)

#----only analyze the samples collected from Plasma
d_plasma <- d[d$Organ == "Plasma", ]

#----controling for all factors
for (i in 1:(varNum)){
  lmfit <- lm(d_plasma[,i+5]~ Smoking_Status + Gender, data = d_plasma)
  pkimodelspvals[[i]] <-   permTS(lmfit$residuals ~ Health_State, data = d_plasma,
                                  alternative="two.sided", method="exact.mc",
                                  control=permControl(nmc=10^5))$p.value
  
  pkimodelseffect[[i]] <-
    mean(2^(d_plasma[d_plasma$Health_State == "Adenocarcinoma",i+5]))/
          mean(2^(d_plasma[d_plasma$Health_State == "Healthy",i+5]))
  pkimodelsmean[[i]] <- mean(d_plasma[d_plasma$Health_State == "Adenocarcinoma",i+5])
  
}

pki_effect = unlist(pkimodelseffect)
FoldChange <- pki_effect
pkimodelsmean <- unlist(pkimodelsmean)

pki_ps_raw = unlist(pkimodelspvals)
plot(log(pki_effect, base = 2), -log(pki_ps_raw, base = 10))
pki_ps_adj <- p.adjust(pki_ps_raw, method = "BH")
plot(log(pki_effect, base = 2), -log(pki_ps_adj, base = 10))

univariate_res_control = data.frame(variables = vars, pvalues = pki_ps_raw,
                                    adj_pvalues = pki_ps_adj,
                                    FoldChange = FoldChange,
                                    pkimodelsmean = pkimodelsmean)
univariate_res_control$significance_raw <- univariate_res_control$pvalues< .05
univariate_res_control$significance_adj <- univariate_res_control$adj_pvalues < .05
write.csv(univariate_res_control, "significance_results/healthstate_anova_wsig_control_training_plasma_nonpara.txt", row.names = F)
```


```{r}
sigs <- read.csv("significance_results/healthstate_anova_wsig_control_training_serum_nonpara.txt")
sum(sigs$significance_raw)
sigs_training <- sigs$variables[(sigs$pvalues < .05) == T]

sigs <- read.csv("significance_results/healthstate_anova_wsig_control_training_plasma_nonpara.txt")
sum(sigs$significance_raw)
sigs_training <- sigs$variables[(sigs$pvalues < .05) == T]

sigs <- read.csv("significance_results/healthstate_anova_wsig_control_training_block.txt")
sum(sigs$significance_raw)
sigs_training <- sigs$variables[(sigs$pvalues < .05) == T]

boxplot(d_serum$xylose~d_serum$Health_State, main = "xylose")
stripchart(d_serum$xylose ~ d_serum$Health_State, vertical = TRUE,
           method = "jitter", add = TRUE, pch = 20, col = 'blue')

boxplot(d_serum$glutamic_acid~d_serum$Health_State, main = "glutamate")
stripchart(d_serum$glutamic_acid~d_serum$Health_State, vertical = TRUE,
           method = "jitter", add = TRUE, pch = 20, col = 'blue')

boxplot(d_serum$aspartic_acid~d_serum$Health_State, main = "aspartate")
stripchart(d_serum$aspartic_acid~d_serum$Health_State, vertical = TRUE,
           method = "jitter", add = TRUE, pch = 20, col = 'blue')

```


# Test Set

```{r}
rm(list = ls())
sdfset <- read.SDFset("common_test_training_molecule-v2.sdf")

# test for significance with only compounds that have chemical structures

f1 <- read.delim(file = "sample_factors_test.txt", header = T, row.names = 1)
f2 <- read.table(file = "sample_metabolites_test.txt", header = T, row.names = 1)
f1 <- na.omit(f1)
rownames(f1) <- f1$Sample_name
f1$Subject_name <- gsub("P_|S_", "", f1$Subject_name, perl = T)

f1 <- f1[, -2]
colnames(f1) <- c("Patient","Organ", "Health_State", "Smoking_Status", "Gender")
head(f1)

f2 <- t(f2)

# save this processed data frame so you can try different processing
before.process <- f2

# two metabolites with missing values, use imputation, take half the minimum
# of that metabolite's value
# also, perform log base 2 transformation.  I cannot for the life of me
# figure out how they did their normalization
# lactic acid had some zero values? impute those too
f2 <- apply(f2, 2, function(x) {
  x[is.na(x)] <- .5*min(na.omit(x))
  x[x == 0] <- .5*min(na.omit(x[x != 0]))
  x
})

# # not necessary to do total quantity normalization
# # pvalues dont change see below
for(i in 1:nrow(f2)){
  f2[i, ] <- f2[i, ]/sum(f2[i, ])
}

# log transformation
f2 <- log(f2, base = 2)

summary(f2[, 1:6])

# fix compound names so that they are the same
# format as the file provided by Melaine
ids <- sdfid(sdfset)
ids.new <- gsub(" |,","_",ids, perl = T)
colnames(f2) <- gsub(" |,","_", colnames(f2), perl = T)

# 130 compounds provided
sum(ids.new %in% colnames(f2))
dim(f2)

f2 <- f2[, colnames(f2) %in% ids.new]
orig.mets <- colnames(f2)[colnames(f2) %in% ids.new]

rownames(f2) <- sub("X", "", row.names(f2))
d <- merge(f1, f2, by.x= "row.names", by.y = "row.names")

d$Organ <- factor(d$Organ)

#replacing mispelled adenocarcinoma and "Adenosquamous" with Adenocarcinoma
d$Health_State <- gsub("Adenocarcnoma|Adenosquamous", "Adenocarcinoma", d$Health_State)
row.names(d) <- d$Row.names
d$Row.names <- NULL
save.image("test_set_tq_nonormalize.rda")
```

## Patient characteristic table

```{r}
table(d$Organ, d$Health_State)
table(d$Organ, d$Smoking_Status)
table(d$Organ, d$Smoking_Status, d$Health_State)
table(d$Organ, d$Gender)
table(d$Organ, d$Gender, d$Health_State)
```

## T-Tests for Significant differences

```{r}

vars = colnames(d)[6:ncol(d)]
varNum <- length(vars)
pkimodels <- vector("list", (varNum))
pkimodelspvals <- vector("list", (varNum))
pkimodelseffect <- vector("list", (varNum))
pkimodelsmean <- vector("list", (varNum))

#----controling for all factors, including organ

for (i in 1:(varNum)){
  lmfit <- lm(d[,i+5]~ Organ + Health_State + Smoking_Status + Gender, data = d)
  pkimodels[[i]] <- lmfit
  #pvalue for regressing each variable in df on AC50
  pkimodelspvals[[i]] <- Anova(lmfit, type = "III")$`Pr(>F)`[3]
  
  pkimodelseffect[[i]] <- log(mean(2^(d[d$Health_State == "Adenocarcinoma",i+5]))/mean(2^(d[d$Health_State == "Healthy",i+5])), base=2)
  # mins[[i]] <- min(d[,220])
}

pki_ps = unlist(pkimodelspvals)
pki_ps <- p.adjust(pki_ps, method = "BH")

pki_effect = unlist(pkimodelseffect)
plot(pki_effect, -log(pki_ps, base = 10))
log2FoldChange <- pki_effect

univariate_res_control = data.frame(variables = vars, pvalues = pki_ps, log2FoldChange = log2FoldChange)
univariate_res_control$significance <- univariate_res_control$pvalues < .05
sig_no_block <- univariate_res_control$pvalues < .05
write.csv(univariate_res_control, "significance_results/healthstate_anova_wsig_control_test.txt", row.names = F)

#-----Using patient as blocking factor

for (i in 1:(varNum)){
  lmfit <- lmer(d[,i+5]~ Organ + Health_State + Smoking_Status + Gender + (1|Patient), data = d)
  pkimodels[[i]] <- lmfit
  #pvalue for regressing each variable in df on AC50
  pkimodelspvals[[i]] <- Anova(lmfit, type = "III")$`Pr(>Chisq)`[3]
  
  pkimodelseffect[[i]] <- mean(2^(d[d$Health_State == "Adenocarcinoma",i+5]))/mean(2^(d[d$Health_State == "Healthy",i+5]))
  # mins[[i]] <- min(d[,220])
}

pki_effect = unlist(pkimodelseffect)
log2FoldChange <- pki_effect

pki_ps_raw = unlist(pkimodelspvals)
plot(log(pki_effect, base = 2), -log(pki_ps_raw, base = 10))
pki_ps_adj <- p.adjust(pki_ps_raw, method = "BH")
plot(log(pki_effect, base = 2), -log(pki_ps_adj, base = 10))

univariate_res_control = data.frame(variables = vars, pvalues = pki_ps_raw,
                                    adj_pvalues = pki_ps_adj,
                                    FoldChange = log2FoldChange)
univariate_res_control$significance_raw <- univariate_res_control$pvalues < .05
univariate_res_control$significance_adj <- univariate_res_control$adj_pvalues < .05
write.csv(univariate_res_control, "significance_results/healthstate_anova_wsig_control_test_block.txt", row.names = F)


#----only analyze the samples collected from Serum
d_serum <- d[d$Organ == "Serum", ]
#----controling for all factors
for (i in 1:(varNum)){
  lmfit <- lm(d_serum[,i+5]~ Health_State + Smoking_Status + Gender, data = d_serum)
  pkimodels[[i]] <- lmfit
  #pvalue for regressing each variable in df on AC50
  pkimodelspvals[[i]] <- Anova(lmfit, type = "III")$`Pr(>F)`[3]
  
  pkimodelseffect[[i]] <- 
    log(mean(2^(d_serum[d_serum$Health_State == "Adenocarcinoma",i+5]))/mean(2^(d_serum[d_serum$Health_State == "Healthy",i+5])), base=2)
  pkimodelsmean[[i]] <- mean(d_serum[d_serum$Health_State == "Adenocarcinoma",i+5])
}

pki_ps = unlist(pkimodelspvals)
pki_ps <- p.adjust(pki_ps, method = "BH")

pki_effect = unlist(pkimodelseffect)
plot(pki_effect, -log(pki_ps, base = 10))
log2FoldChange <- pki_effect
pkimodelsmean <- unlist(pkimodelsmean)

univariate_res_control = data.frame(variables = vars, pvalues = pki_ps,
                                    log2FoldChange = log2FoldChange, 
                                    pkimodelsmean = pkimodelsmean)
univariate_res_control$significance <- univariate_res_control$pvalues < .05

# # use FDR of .2 instead
# pki_ps[which(univariate_res_control$pvalues < .2)]
# univariate_res_control$significance <- univariate_res_control$pvalues < .2
sum(univariate_res_control$significance)
write.csv(univariate_res_control, "significance_results/healthstate_anova_wsig_control_test_serum.txt", row.names = F)

#----only analyze the samples collected from plasma
d_plasma <- d[d$Organ == "Plasma", ]

#----controling for all factors
for (i in 1:(varNum)){
  lmfit <- lm(d_plasma[,i+5]~ Health_State + Smoking_Status + Gender, data = d_plasma)
  pkimodels[[i]] <- lmfit
  #pvalue for regressing each variable in df on AC50
  pkimodelspvals[[i]] <- Anova(lmfit, type = "III")$`Pr(>F)`[3]
  
  pkimodelseffect[[i]] <- 
    log(mean(2^(d_plasma[d_plasma$Health_State == "Adenocarcinoma",i+5]))/
          mean(2^(d_plasma[d_plasma$Health_State == "Healthy",i+5])), base=2)
  pkimodelsmean[[i]] <- mean(d_plasma[d_plasma$Health_State == "Adenocarcinoma",i+5])
  
}

pki_ps = unlist(pkimodelspvals)
pki_ps <- p.adjust(pki_ps, method = "BH")

pki_effect = unlist(pkimodelseffect)
plot(pki_effect, -log(pki_ps, base = 10))
log2FoldChange <- pki_effect
pkimodelsmean <- unlist(pkimodelsmean)

univariate_res_control = data.frame(variables = vars, pvalues = pki_ps,
                                    log2FoldChange = log2FoldChange, 
                                    pkimodelsmean = pkimodelsmean)
univariate_res_control$significance <- univariate_res_control$pvalues < .05
sum(univariate_res_control$significance)
write.csv(univariate_res_control, "significance_results/healthstate_anova_wsig_control_test_plasma.txt", row.names = F)

```

## Non-parameteric approach

```{r, cache=T}
#----only analyze the samples collected from Serum
d_serum <- d[d$Organ == "Serum", ]
#----controling for all factors
for (i in 1:(varNum)){
  lmfit <- lm(d_serum[,i+5]~ Smoking_Status + Gender, data = d_serum)
  pkimodelspvals[[i]] <-   permTS(lmfit$residuals ~ Health_State, data = d_serum,
                                  alternative="two.sided", method="exact.mc",
                                  control=permControl(nmc=10^5))$p.value
  # Switched to reporting FC instead of logFC here so that can get right input for volcano plot
  # on metabolomics workbench
  pkimodelseffect[[i]] <-
    mean(2^(d_serum[d_serum$Health_State == "Adenocarcinoma",i+5]))/mean(2^(d_serum[d_serum$Health_State == "Healthy",i+5]))
  pkimodelsmean[[i]] <- mean(d_plasma[d_plasma$Health_State == "Adenocarcinoma",i+5])
}

pki_effect = unlist(pkimodelseffect)
FoldChange <- pki_effect
pkimodelsmean <- unlist(pkimodelsmean)

pki_ps_raw = unlist(pkimodelspvals)
plot(log(pki_effect, base = 2), -log(pki_ps_raw, base = 10))
pki_ps_adj <- p.adjust(pki_ps_raw, method = "BH")
plot(log(pki_effect, base = 2), -log(pki_ps_adj, base = 10))

univariate_res_control = data.frame(variables = vars, pvalues = pki_ps_raw,
                                    adj_pvalues = pki_ps_adj,
                                    FoldChange = FoldChange,
                                    pkimodelsmean = pkimodelsmean)
univariate_res_control$significance_raw <- univariate_res_control$pvalues < .05
univariate_res_control$significance_adj <- univariate_res_control$adj_pvalues < .05
write.csv(univariate_res_control, "significance_results/healthstate_anova_wsig_control_test_serum_nonpara.txt", row.names = F)

#----only analyze the samples collected from Plasma
d_plasma <- d[d$Organ == "Plasma", ]

#----controling for all factors
for (i in 1:(varNum)){
  lmfit <- lm(d_plasma[,i+5]~ Smoking_Status + Gender, data = d_plasma)
  pkimodelspvals[[i]] <-   permTS(lmfit$residuals ~ Health_State, data = d_plasma,
                                  alternative="two.sided", method="exact.mc",
                                  control=permControl(nmc=10^5))$p.value
  
  pkimodelseffect[[i]] <-
    mean(2^(d_plasma[d_plasma$Health_State == "Adenocarcinoma",i+5]))/
          mean(2^(d_plasma[d_plasma$Health_State == "Healthy",i+5]))
  pkimodelsmean[[i]] <- mean(d_plasma[d_plasma$Health_State == "Adenocarcinoma",i+5])
  
}

pki_effect = unlist(pkimodelseffect)
FoldChange <- pki_effect
pkimodelsmean <- unlist(pkimodelsmean)

pki_ps_raw = unlist(pkimodelspvals)
plot(log(pki_effect, base = 2), -log(pki_ps_raw, base = 10))
pki_ps_adj <- p.adjust(pki_ps_raw, method = "BH")
plot(log(pki_effect, base = 2), -log(pki_ps_adj, base = 10))

univariate_res_control = data.frame(variables = vars, pvalues = pki_ps_raw,
                                    adj_pvalues = pki_ps_adj,
                                    FoldChange = FoldChange,
                                    pkimodelsmean = pkimodelsmean)
univariate_res_control$significance_raw <- univariate_res_control$pvalues< .05
univariate_res_control$significance_adj <- univariate_res_control$adj_pvalues < .05
write.csv(univariate_res_control, "significance_results/healthstate_anova_wsig_control_test_plasma_nonpara.txt", row.names = F)
```


```{r}
sigs <- read.csv("significance_results/healthstate_anova_wsig_control_test_serum_nonpara.txt")
sum(sigs$significance_raw)
sigs_test <- sigs$variables[(sigs$pvalues < .05) == T]

sigs <- read.csv("significance_results/healthstate_anova_wsig_control_test_plasma_nonpara.txt")
sum(sigs$significance_raw)
sigs_test <- sigs$variables[(sigs$pvalues < .05) == T]

sigs <- read.csv("significance_results/healthstate_anova_wsig_control_test_block.txt")
sum(sigs$significance_raw)
sigs_test <- sigs$variables[(sigs$pvalues < .05) == T]

boxplot(d_serum$xylose~d_serum$Health_State, main = "xylose")
stripchart(d_serum$xylose ~ d_serum$Health_State, vertical = TRUE,
           method = "jitter", add = TRUE, pch = 20, col = 'blue')

boxplot(d_serum$glutamic_acid~d_serum$Health_State, main = "glutamate")
stripchart(d_serum$glutamic_acid~d_serum$Health_State, vertical = TRUE,
           method = "jitter", add = TRUE, pch = 20, col = 'blue')

boxplot(d_serum$aspartic_acid~d_serum$Health_State, main = "aspartate")
stripchart(d_serum$aspartic_acid~d_serum$Health_State, vertical = TRUE,
           method = "jitter", add = TRUE, pch = 20, col = 'blue')

```


