---
title: "Metabolomics ML results"
author: "Jeremy Ash"
date: "October 13, 2018"
output:
  html_document:
    toc: true
    toc_float: true
    number_sections: true
    collapsed: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(caret)
library(glmnet)
library(doParallel)
library(pROC)
library(knitr)
library(kableExtra)

cl <- makeCluster(4)
registerDoParallel(cl)

setwd("H:/My Drive/FourchesLab/metabolimics/significant_metabolites")
source("metab_classifier_functions_serum.r")
```

## All metabolites

```{r cars}
load("ML_data.RDATA")
```

### Lasso

```{r, cache = T }
all.acc <- matrix(nrow = 6, ncol = 8)
colnames(all.acc) <- c(rep("LOOCV", 4), rep("External", 4))
colnames(all.acc) <- paste(colnames(all.acc), rep(c("ACC", "SEN", "SPE", "AUC"), 2))
rownames(all.acc) <- c("Lasso", "Logit Boost", "SVM", "RF", "PLS", "xgbTree")

health_df_serum_full <- health_df_serum_full[, -c(2, 3)]
health_df_serum_full.test <- health_df_serum_full.test[, -c(2, 3)]

all.acc <- FitLasso(health_df_serum_full, health_df_serum_full.test, all.acc)
all.acc
```

### Other ML

```{r}
data <- health_df_serum_full
data$Health_State <- as.factor(ifelse(data$Health_State == 0, "neg", "pos"))

data.test <- health_df_serum_full.test
data.test$Health_State <- as.factor(ifelse(data.test$Health_State == 0, "neg", "pos"))
```

```{r, cache = T}
all.acc <- FitMlmodels(data, data.test, all.acc)
```

```{r}
all.acc %>%  kable() %>%  kable_styling()
write.csv(all.acc, file = "serum_all_met_acc.csv")
```

## Significant metabolites

### Lasso

```{r, cache = T }
all.acc <- matrix(nrow = 6, ncol = 8)
colnames(all.acc) <- c(rep("LOOCV", 4), rep("External", 4))
colnames(all.acc) <- paste(colnames(all.acc), rep(c("ACC", "SEN", "SPE", "AUC"), 2))
rownames(all.acc) <- c("Lasso", "Logit Boost", "SVM", "RF", "PLS", "xgbTree")

health_df_serum_full <- health_df_serum_full[, c(1, serum.met.idx - 3)]
health_df_serum_full.test <- health_df_serum_full.test[, c(1, serum.met.idx - 3)]

all.acc <- FitLasso(health_df_serum_full, health_df_serum_full.test, all.acc)
```

### Other ML

```{r}
data <- health_df_serum_full
data$Health_State <- as.factor(ifelse(data$Health_State == 0, "neg", "pos"))

data.test <- health_df_serum_full.test
data.test$Health_State <- as.factor(ifelse(data.test$Health_State == 0, "neg", "pos"))
```

```{r, cache = T}
all.acc <- FitMlmodels(data, data.test, all.acc)
```

```{r}
all.acc %>%  kable() %>%  kable_styling()
write.csv(all.acc, file = "serum_sig_met_acc.csv")
```

## Cluster metabolites

### Lasso

```{r, cache = T }
all.acc <- matrix(nrow = 6, ncol = 8)
colnames(all.acc) <- c(rep("LOOCV", 4), rep("External", 4))
colnames(all.acc) <- paste(colnames(all.acc), rep(c("ACC", "SEN", "SPE", "AUC"), 2))
rownames(all.acc) <- c("Lasso", "Logit Boost", "SVM", "RF", "PLS", "xgbTree")

health_df_serum_full <- health_df_serum_full[, c(1, 2, 3, 4)]
health_df_serum_full.test <- health_df_serum_full.test[, c(1, 2, 3, 4)]

all.acc <- FitLasso(health_df_serum_full, health_df_serum_full.test, all.acc)
```

### Other ML

```{r}
data <- health_df_serum_full
data$Health_State <- as.factor(ifelse(data$Health_State == 0, "neg", "pos"))

data.test <- health_df_serum_full.test
data.test$Health_State <- as.factor(ifelse(data.test$Health_State == 0, "neg", "pos"))
```

```{r, cache = T}
all.acc <- FitMlmodels(data, data.test, all.acc)
```

```{r}
all.acc %>%  kable() %>%  kable_styling()
write.csv(all.acc, file = "serum_cluster_acc.csv")
```

<!-- ### Lasso -->

<!-- ```{r, cache=T} -->
<!-- sig.acc <- matrix(nrow = 6, ncol = 2) -->
<!-- colnames(sig.acc) <- c("LOOCV", "External") -->
<!-- rownames(sig.acc) <- c("Lasso", "Logit Boost", "SVM", "RF", "PLS", "xgbTree") -->


<!-- # cml.clus.serum <- ModelTrain(health_df_serum_full) -->
<!-- # CombineSplits(cml.clus.serum, metric = "error rate") -->

<!-- cor.cols <- findCorrelation(cor(data.matrix(health_df_serum_full)), cutoff = .9) -->
<!-- cor.cols -->

<!-- x = model.matrix(Health_State ~ ., data = health_df_serum_full)[,-1] -->
<!-- y = health_df_serum_full$Health_State -->
<!-- grid = 10^seq(10, -2, length = 100) -->

<!-- lasso.mod <- glmnet(x, y, family = "binomial", alpha = 1, lambda = grid) -->
<!-- plot(lasso.mod) -->

<!-- set.seed(835) -->
<!-- cv.out = cv.glmnet(x, y, family="binomial", alpha = 1, type.measure="class", nfolds = 80) -->
<!-- bestlam = cv.out$lambda.min -->
<!-- bestlam -->

<!-- # LOOCV accuracy -->
<!-- sig.acc[1, 1] <- 1 - min(cv.out$cvm) -->

<!-- plot(cv.out) -->

<!-- cv.coef <- coef(cv.out, s = bestlam) -->
<!-- cv.coef <- as.matrix(Matrix(cv.coef, sparse = F)) -->
<!-- cv.coef[cv.coef != 0, ] -->

<!-- # prediction performance on test set -->

<!-- big.df.test.singles <- health_df_serum_full.test -->

<!-- #remove correlated columns -->

<!-- # big.df.test.singles <- big.df.test.singles[, -cor.cols] -->
<!-- x.test = model.matrix(Health_State ~ ., data = big.df.test.singles)[, -1] -->
<!-- y.test = big.df.test.singles$Health_State -->
<!-- lasso.pred <- predict(lasso.mod, s = bestlam, newx = x.test, type = "class") -->
<!-- lasso.pred <- as.numeric(lasso.pred[, 1]) -->

<!-- # test accuracy -->
<!-- sig.acc[1, 2] <- mean(lasso.pred == y.test) -->

<!-- # specificity.test -->
<!-- idx <- y.test == 0 -->
<!-- mean(y.test[idx] == lasso.pred[idx]) -->

<!-- # sensitivity.test -->
<!-- idx <- y.test == 1 -->
<!-- mean(y.test[idx] == lasso.pred[idx]) -->
<!-- ``` -->

<!-- ### Other ML -->

<!-- ```{r} -->
<!-- data <- health_df_serum_full -->
<!-- data$Health_State <- as.factor(ifelse(data$Health_State == 0, "neg", "pos")) -->

<!-- data.test <- big.df.test.singles -->
<!-- data.test$Health_State <- as.factor(ifelse(data.test$Health_State == 0, "neg", "pos")) -->
<!-- ``` -->

<!-- ```{r, cache = T} -->
<!-- for (i in 1:5) { -->
<!--   set.seed(9) -->
<!--   if (i != 2) { -->
<!--     model.fit <- train(Health_State~., method=models[i], data=data, metric = "Accmax", -->
<!--                    trControl = fitControl, tuneLength = 10) -->
<!--   } else { -->
<!--     svmGrid <- expand.grid(sigma= 2^c(-25, -20, -15,-10, -5, 0), C= 2^c(0:5)) -->
<!--     model.fit <- train(Health_State~., method=models[i], data=data, metric = "Accmax", -->
<!--                      trControl = fitControl, tuneGrid = svmGrid) -->
<!--     sigma <- log(model.fit$bestTune$sigma, base = 2) -->
<!--     C <- log(model.fit$bestTune$C, base = 2) -->
<!--     set.seed(9) -->
<!--     svmGrid <- expand.grid(sigma= 2^seq(sigma - .5, sigma + .5, length.out = 10), -->
<!--                            C= 2^seq(C - 1, C + 1, length.out = 10)) -->
<!--     model.fit <- train(Health_State~., method=models[i], data=data, metric = "Accmax", -->
<!--                      trControl = fitControl, tuneGrid = svmGrid) -->
<!--   } -->

<!--   maxcv <- max(model.fit$results$Accmax) -->

<!--   # Need to find the threshold -->
<!--   mod.pred <- as.data.frame(model.fit$pred[, 6:ncol(model.fit$pred)]) -->
<!--   tune.par <- model.fit$bestTune -->
<!--   fix.order <- order(names(model.fit$bestTune)) -->
<!--   tune.par <- tune.par[fix.order] -->
<!--   fix.order <- order(colnames(mod.pred)) -->
<!--   mod.pred <- as.data.frame(mod.pred[, fix.order]) -->

<!--   sel <- vector(length = nrow(mod.pred)) -->
<!--   for (i in 1:nrow(mod.pred)) { -->
<!--     sel[i] <- all(mod.pred[i, ] == tune.par) -->
<!--   } -->

<!--   acclist <- as.numeric() -->
<!--   for(i in seq(0.01, 0.99, 0.001)){ -->
<!--     predi <- factor(ifelse(model.fit$pred[sel, "pos"] >= i, "pos", "neg"), levels = c("pos", "neg")) -->
<!--     singleacc <- mean(predi == model.fit$pred$obs[sel]) -->
<!--     acclist <- c(acclist, singleacc) -->
<!--   } -->
<!--   maxcv <- max(acclist) -->
<!--   thresh <- seq(0.01, 0.99, 0.001)[which.max(acclist)] -->

<!--   # LOOCV -->
<!--   sig.acc[i+1, 1] <- maxcv -->

<!--   probs.test <- predict.train(model.fit, data.test, type = "prob") -->
<!--   pred.test <- ifelse(probs.test$pos > thresh, "pos", "neg") -->

<!--   # External Accuracy -->
<!--   sig.acc[i+1, 2] <-  mean(pred.test == data.test$Health_State) -->
<!-- }  -->

<!-- sig.acc %>%  kable() %>%  kable_styling() -->
<!-- ``` -->

<!-- ## Cluster metabolites -->

<!-- ### Lasso -->

<!-- ```{r, cache=T} -->
<!-- clus.acc <- matrix(nrow = 6, ncol = 2) -->
<!-- colnames(clus.acc) <- c("LOOCV", "External") -->
<!-- rownames(clus.acc) <- c("Lasso", "Logit Boost", "SVM", "RF", "PLS", "xgbTree") -->

<!-- health_df_serum_full <- health_df_serum_full[, c(1, 2, 3, 4)] -->
<!-- health_df_serum_full.test <- health_df_serum_full.test[, c(1, 2, 3, 4)] -->
<!-- # cml.clus.serum <- ModelTrain(health_df_serum_full) -->
<!-- # CombineSplits(cml.clus.serum, metric = "error rate") -->

<!-- cor.cols <- findCorrelation(cor(data.matrix(health_df_serum_full)), cutoff = .9) -->
<!-- cor.cols -->

<!-- x = model.matrix(Health_State ~ ., data = health_df_serum_full)[,-1] -->
<!-- y = health_df_serum_full$Health_State -->
<!-- grid = 10^seq(10, -2, length = 100) -->

<!-- lasso.mod <- glmnet(x, y, family = "binomial", alpha = 1, lambda = grid) -->
<!-- plot(lasso.mod) -->

<!-- set.seed(835) -->
<!-- cv.out = cv.glmnet(x, y, family="binomial", alpha = 1, type.measure="class", nfolds = 80) -->
<!-- bestlam = cv.out$lambda.min -->
<!-- bestlam -->

<!-- # LOOCV accuracy -->
<!-- clus.acc[1, 1] <- 1 - min(cv.out$cvm) -->

<!-- plot(cv.out) -->

<!-- cv.coef <- coef(cv.out, s = bestlam) -->
<!-- cv.coef <- as.matrix(Matrix(cv.coef, sparse = F)) -->
<!-- cv.coef[cv.coef != 0, ] -->

<!-- # prediction performance on test set -->

<!-- big.df.test.singles <- health_df_serum_full.test -->

<!-- #remove correlated columns -->

<!-- # big.df.test.singles <- big.df.test.singles[, -cor.cols] -->
<!-- x.test = model.matrix(Health_State ~ ., data = big.df.test.singles)[, -1] -->
<!-- y.test = big.df.test.singles$Health_State -->
<!-- lasso.pred <- predict(lasso.mod, s = bestlam, newx = x.test, type = "class") -->
<!-- lasso.pred <- as.numeric(lasso.pred[, 1]) -->

<!-- # test accuracy -->
<!-- clus.acc[1, 2] <- mean(lasso.pred == y.test) -->

<!-- # specificity.test -->
<!-- idx <- y.test == 0 -->
<!-- mean(y.test[idx] == lasso.pred[idx]) -->

<!-- # sensitivity.test -->
<!-- idx <- y.test == 1 -->
<!-- mean(y.test[idx] == lasso.pred[idx]) -->
<!-- ``` -->

<!-- ### Other ML -->

<!-- ```{r} -->
<!-- data <- health_df_serum_full -->
<!-- data$Health_State <- as.factor(ifelse(data$Health_State == 0, "neg", "pos")) -->

<!-- data.test <- big.df.test.singles -->
<!-- data.test$Health_State <- as.factor(ifelse(data.test$Health_State == 0, "neg", "pos")) -->
<!-- ``` -->

<!-- # ```{r, cache = T} -->
<!-- # mat = lapply(c("LogitBoost", 'svmRadial', 'rf', 'pls', 'xgbTree'),  -->
<!-- #              function (met) { -->
<!-- #                set.seed(830) -->
<!-- #                train(Health_State~., method=met, data=data, tuneLength = 10, metric = "Accmax", -->
<!-- #                      trControl = fitControl) -->
<!-- #              }) -->
<!-- # mat.clus <- mat -->
<!-- # ``` -->

<!-- ```{r, cache = T} -->
<!-- for (i in 1:5) { -->
<!--   set.seed(9) -->
<!--   if (i != 2) { -->
<!--     model.fit <- train(Health_State~., method=models[i], data=data, metric = "Accmax", -->
<!--                    trControl = fitControl, tuneLength = 10) -->
<!--   } else { -->
<!--     svmGrid <- expand.grid(sigma= 2^c(-25, -20, -15,-10, -5, 0), C= 2^c(0:5)) -->
<!--     model.fit <- train(Health_State~., method=models[i], data=data, metric = "Accmax", -->
<!--                      trControl = fitControl, tuneGrid = svmGrid) -->
<!--     sigma <- log(model.fit$bestTune$sigma, base = 2) -->
<!--     C <- log(model.fit$bestTune$C, base = 2) -->
<!--     set.seed(9) -->
<!--     svmGrid <- expand.grid(sigma= 2^seq(sigma - .5, sigma + .5, length.out = 10), -->
<!--                            C= 2^seq(C - 1, C + 1, length.out = 10)) -->
<!--     model.fit <- train(Health_State~., method=models[i], data=data, metric = "Accmax", -->
<!--                      trControl = fitControl, tuneGrid = svmGrid) -->
<!--   } -->

<!--   maxcv <- max(model.fit$results$Accmax) -->

<!--   # Need to find the threshold -->
<!--   mod.pred <- as.data.frame(model.fit$pred[, 6:ncol(model.fit$pred)]) -->
<!--   tune.par <- model.fit$bestTune -->
<!--   fix.order <- order(names(model.fit$bestTune)) -->
<!--   tune.par <- tune.par[fix.order] -->
<!--   fix.order <- order(colnames(mod.pred)) -->
<!--   mod.pred <- as.data.frame(mod.pred[, fix.order]) -->

<!--   sel <- vector(length = nrow(mod.pred)) -->
<!--   for (i in 1:nrow(mod.pred)) { -->
<!--     sel[i] <- all(mod.pred[i, ] == tune.par) -->
<!--   } -->

<!--   acclist <- as.numeric() -->
<!--   for(i in seq(0.01, 0.99, 0.001)){ -->
<!--     predi <- factor(ifelse(model.fit$pred[sel, "pos"] >= i, "pos", "neg"), levels = c("pos", "neg")) -->
<!--     singleacc <- mean(predi == model.fit$pred$obs[sel]) -->
<!--     acclist <- c(acclist, singleacc) -->
<!--   } -->
<!--   maxcv <- max(acclist) -->
<!--   thresh <- seq(0.01, 0.99, 0.001)[which.max(acclist)] -->

<!--   # LOOCV -->
<!--   clus.acc[i+1, 1] <- maxcv -->

<!--   probs.test <- predict.train(model.fit, data.test, type = "prob") -->
<!--   pred.test <- ifelse(probs.test$pos > thresh, "pos", "neg") -->

<!--   # External Accuracy -->
<!--   clus.acc[i+1, 2] <-  mean(pred.test == data.test$Health_State) -->
<!-- }  -->

<!-- clus.acc %>%  kable() %>%  kable_styling() -->
<!-- ``` -->
