---
title: "Metabolomics ML results -- Plasma"
author: "Jeremy Ash"
date: "October 13, 2018"
output:
  html_document:
    toc: true
    toc_float: true
    number_sections: true
    collapsed: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(caret)
library(glmnet)
library(doParallel)
library(pROC)
library(knitr)
library(kableExtra)

cl <- makeCluster(4)
registerDoParallel(cl)

setwd("G:/My Drive/FourchesLab/metabolimics/significant_metabolites")
source("metab_classifier_functions_plasma.r")
```

## All metabolites

```{r cars}
load("ML_data.RDATA")
```

### Lasso

```{r, cache = T }
all.acc <- matrix(nrow = 6, ncol = 8)
colnames(all.acc) <- c(rep("LOOCV", 4), rep("External", 4))
colnames(all.acc) <- paste(colnames(all.acc), rep(c("ACC", "SEN", "SPE", "AUC"), 2))
rownames(all.acc) <- c("Lasso", "Logit Boost", "SVM", "RF", "PLS", "xgbTree")

health_df_plasma_full <- health_df_plasma_full[, -c(2, 3)]
health_df_plasma_full.test <- health_df_plasma_full.test[, -c(2, 3)]

all.acc <- FitLasso(health_df_plasma_full, health_df_plasma_full.test, all.acc)
```

### Other ML

```{r}
data <- health_df_plasma_full
data$Health_State <- as.factor(ifelse(data$Health_State == 0, "neg", "pos"))

data.test <- health_df_plasma_full.test
data.test$Health_State <- as.factor(ifelse(data.test$Health_State == 0, "neg", "pos"))
```

```{r, cache = T}
all.acc <- FitMlmodels(data, data.test, all.acc)
```

```{r}
all.acc %>%  kable() %>%  kable_styling()
write.csv(all.acc, file = "plasma_all_met_acc.csv")
```

## Significant metabolites

### Lasso

```{r, cache = T }
all.acc <- matrix(nrow = 6, ncol = 8)
colnames(all.acc) <- c(rep("LOOCV", 4), rep("External", 4))
colnames(all.acc) <- paste(colnames(all.acc), rep(c("ACC", "SEN", "SPE", "AUC"), 2))
rownames(all.acc) <- c("Lasso", "Logit Boost", "SVM", "RF", "PLS", "xgbTree")

health_df_plasma_sig <- health_df_plasma_full[, c(1, plasma.met.idx - 3)]
health_df_plasma_sig.test <- health_df_plasma_full.test[, c(1, plasma.met.idx - 3)]

all.acc <- FitLasso(health_df_plasma_sig, health_df_plasma_sig.test, all.acc)
```

### Other ML

```{r}
data <- health_df_plasma_sig
data$Health_State <- as.factor(ifelse(data$Health_State == 0, "neg", "pos"))

data.test <- health_df_plasma_sig.test
data.test$Health_State <- as.factor(ifelse(data.test$Health_State == 0, "neg", "pos"))
```

```{r, cache = T}
all.acc <- FitMlmodels(data, data.test, all.acc)
```

```{r}
all.acc %>%  kable() %>%  kable_styling()
write.csv(all.acc, file = "plasma_sig_met_acc.csv")
```

## Cluster 1 metabolites

### Lasso

```{r, cache = T}
all.acc <- matrix(nrow = 6, ncol = 8)
colnames(all.acc) <- c(rep("LOOCV", 4), rep("External", 4))
colnames(all.acc) <- paste(colnames(all.acc), rep(c("ACC", "SEN", "SPE", "AUC"), 2))
rownames(all.acc) <- c("Lasso", "Logit Boost", "SVM", "RF", "PLS", "xgbTree")

health_df_plasma_clus1 <- health_df_plasma_sig[, c(1, 2, 10)]
health_df_plasma_clus1.test <- health_df_plasma_sig.test[, c(1, 2, 10)]
head(health_df_plasma_clus1)

all.acc <- FitLasso(health_df_plasma_clus1, health_df_plasma_clus1.test, all.acc)
```

### Other ML

```{r}
data <- health_df_plasma_clus1
data$Health_State <- as.factor(ifelse(data$Health_State == 0, "neg", "pos"))

data.test <- health_df_plasma_clus1.test
data.test$Health_State <- as.factor(ifelse(data.test$Health_State == 0, "neg", "pos"))
```

```{r, cache = T}
all.acc <- FitMlmodels(data, data.test, all.acc)
```

```{r}
all.acc %>%  kable() %>%  kable_styling()
write.csv(all.acc, file = "plasma_clus1_met_acc.csv")
```

## Cluster 2 metabolites

### Lasso

```{r, cache = T }
all.acc <- matrix(nrow = 6, ncol = 8)
colnames(all.acc) <- c(rep("LOOCV", 4), rep("External", 4))
colnames(all.acc) <- paste(colnames(all.acc), rep(c("ACC", "SEN", "SPE", "AUC"), 2))
rownames(all.acc) <- c("Lasso", "Logit Boost", "SVM", "RF", "PLS", "xgbTree")

health_df_plasma_clus2 <- health_df_plasma_sig[, c(1, 4, 5, 6, 7)]
health_df_plasma_clus2.test <- health_df_plasma_sig.test[, c(1, 4, 5, 6, 7)]
head(health_df_plasma_clus2)

all.acc <- FitLasso(health_df_plasma_clus2, health_df_plasma_clus2.test, all.acc)
```

### Other ML

```{r}
data <- health_df_plasma_clus2
data$Health_State <- as.factor(ifelse(data$Health_State == 0, "neg", "pos"))

data.test <- health_df_plasma_clus2.test
data.test$Health_State <- as.factor(ifelse(data.test$Health_State == 0, "neg", "pos"))
```

```{r, cache = T}
all.acc <- FitMlmodels(data, data.test, all.acc)
```

```{r}
all.acc %>%  kable() %>%  kable_styling()
write.csv(all.acc, file = "plasma_clus2_met_acc.csv")
```

## Cluster 3 metabolites

### Lasso

```{r, cache = T }
all.acc <- matrix(nrow = 6, ncol = 8)
colnames(all.acc) <- c(rep("LOOCV", 4), rep("External", 4))
colnames(all.acc) <- paste(colnames(all.acc), rep(c("ACC", "SEN", "SPE", "AUC"), 2))
rownames(all.acc) <- c("Lasso", "Logit Boost", "SVM", "RF", "PLS", "xgbTree")

health_df_plasma_clus3 <- health_df_plasma_sig[, c(1, 8, 9)]
health_df_plasma_clus3.test <- health_df_plasma_sig.test[, c(1, 8, 9)]
head(health_df_plasma_clus3)

all.acc <- FitLasso(health_df_plasma_clus3, health_df_plasma_clus3.test, all.acc)
```

### Other ML

```{r}
data <- health_df_plasma_clus3
data$Health_State <- as.factor(ifelse(data$Health_State == 0, "neg", "pos"))

data.test <- health_df_plasma_clus3.test
data.test$Health_State <- as.factor(ifelse(data.test$Health_State == 0, "neg", "pos"))
```

```{r, cache = T}
all.acc <- FitMlmodels(data, data.test, all.acc)
```

```{r}
all.acc %>%  kable() %>%  kable_styling()
write.csv(all.acc, file = "plasma_clus3_met_acc.csv")
```



<!-- --- -->
<!-- title: "Metabolomics ML results - Plasma" -->
<!-- author: "Jeremy Ash" -->
<!-- date: "October 13, 2018" -->
<!-- output: -->
<!--   html_document: -->
<!--     toc: true -->
<!--     toc_float: true -->
<!--     number_sections: true -->
<!--     collapsed: false -->
<!-- --- -->

<!-- ```{r setup, include=FALSE} -->
<!-- knitr::opts_chunk$set(echo = TRUE) -->
<!-- library(caret) -->
<!-- library(glmnet) -->
<!-- library(doParallel) -->
<!-- library(pROC) -->
<!-- library(knitr) -->
<!-- library(kableExtra) -->

<!-- cl <- makeCluster(4) -->
<!-- registerDoParallel(cl) -->

<!-- setwd("H:/My Drive/FourchesLab/metabolimics/significant_metabolites") -->

<!-- rm(list = ls()) -->
<!-- ``` -->

<!-- ## All metabolites -->

<!-- ```{r cars} -->
<!-- load("ML_data.RDATA") -->
<!-- ``` -->



<!-- ### Lasso -->

<!-- ```{r, cache = T } -->
<!-- all.acc <- matrix(nrow = 6, ncol = 2) -->
<!-- colnames(all.acc) <- c("LOOCV", "External") -->
<!-- rownames(all.acc) <- c("Lasso", "Logit Boost", "SVM", "RF", "PLS", "xgbTree") -->

<!-- health_df_plasma_full <- health_df_plasma_full[, -c(2, 3)] -->
<!-- health_df_plasma_full.test <- health_df_plasma_full.test[, -c(2, 3)] -->
<!-- # cml.clus.plasma <- ModelTrain(health_df_plasma_full) -->
<!-- # CombineSplits(cml.clus.plasma, metric = "error rate") -->

<!-- cor.cols <- findCorrelation(cor(data.matrix(health_df_plasma_full)), cutoff = .9) -->
<!-- cor.cols -->

<!-- x = model.matrix(Health_State ~ ., data = health_df_plasma_full)[,-1] -->
<!-- y = health_df_plasma_full$Health_State -->
<!-- grid = 10^seq(10, -2, length = 100) -->

<!-- lasso.mod <- glmnet(x, y, family = "binomial", alpha = 1, lambda = grid) -->
<!-- plot(lasso.mod) -->

<!-- set.seed(835) -->
<!-- cv.out = cv.glmnet(x, y, family="binomial", alpha = 1, type.measure="class", nfolds = 82) -->
<!-- bestlam = cv.out$lambda.min -->
<!-- bestlam -->

<!-- # LOOCV accuracy -->
<!-- all.acc[1, 1] <- 1 - min(cv.out$cvm) -->

<!-- plot(cv.out) -->

<!-- cv.coef <- coef(cv.out, s = bestlam) -->
<!-- cv.coef <- as.matrix(Matrix(cv.coef, sparse = F)) -->
<!-- cv.coef[cv.coef != 0, ] -->

<!-- # prediction performance on test set -->

<!-- big.df.test.singles <- health_df_plasma_full.test -->

<!-- #remove correlated columns -->

<!-- # big.df.test.singles <- big.df.test.singles[, -cor.cols] -->
<!-- x.test = model.matrix(Health_State ~ ., data = big.df.test.singles)[, -1] -->
<!-- y.test = big.df.test.singles$Health_State -->
<!-- lasso.pred <- predict(lasso.mod, s = bestlam, newx = x.test, type = "class") -->
<!-- lasso.pred <- as.numeric(lasso.pred[, 1]) -->

<!-- # test accuracy -->
<!-- mean(lasso.pred == y.test) -->
<!-- all.acc[1, 2] <- mean(lasso.pred == y.test) -->

<!-- # specificity.test -->
<!-- idx <- y.test == 0 -->
<!-- mean(y.test[idx] == lasso.pred[idx]) -->

<!-- # sensitivity.test -->
<!-- idx <- y.test == 1 -->
<!-- mean(y.test[idx] == lasso.pred[idx]) -->
<!-- ``` -->

<!-- ### Fit parameters -->

<!-- ```{r} -->
<!-- customSummary <- function (data, lev = NULL, model = NULL){ -->
<!--   spec <- specificity(data[, "pred"], data[, "obs"], lev[2]) -->
<!--   pred <- factor(ifelse(data[, "neg"] > 0.5, "neg", "pos")) -->
<!--   spec2 <- specificity(pred, data[, "obs"], "pos") -->
<!--   acclist <- as.numeric() -->
<!--   for(i in seq(0.01, 0.99, 0.01)){ -->
<!--     predi <- factor(ifelse(data[, "neg"] > i, "neg", "pos"), levels = c("neg", "pos")) -->
<!--     singleacc <- mean(predi == data[, "obs"]) -->
<!--     acclist <- c(acclist, singleacc) -->
<!--   } -->
<!--   max(acclist) -> accmax -->

<!--   out <- c(spec, spec2, accmax) -->

<!--   names(out) <- c("Spec", "Spec2", "Accmax") -->
<!--   out -->
<!-- } -->

<!-- fitControl <- trainControl(method = "LOOCV", classProbs = TRUE, savePredictions = TRUE, -->
<!--                            summaryFunction = customSummary) -->
<!-- ``` -->

<!-- ### Other ML -->

<!-- ```{r} -->
<!-- data <- health_df_plasma_full -->
<!-- data$Health_State <- as.factor(ifelse(data$Health_State == 0, "neg", "pos")) -->

<!-- data.test <- big.df.test.singles -->
<!-- data.test$Health_State <- as.factor(ifelse(data.test$Health_State == 0, "neg", "pos")) -->
<!-- ``` -->

<!-- ```{r, cache = T} -->
<!-- mat = lapply(c("LogitBoost", 'svmRadial', 'rf', 'pls', 'xgbTree'),  -->
<!--              function (met) { -->
<!--                set.seed(830) -->
<!--                train(Health_State~., method=met, data=data, tuneLength = 10, metric = "Accmax", -->
<!--                      trControl = fitControl) -->
<!--              }) -->

<!-- ``` -->

<!-- ```{r, cache = T} -->
<!-- svmGrid <- expand.grid(sigma= 2^c(-25, -20, -15,-10, -5, 0), -->
<!--                        C= 2^c(0:5)) -->
<!-- set.seed(45)  -->
<!-- mat.all[[2]] <- train(Health_State~., data = data,  -->
<!--                        method = "svmRadial", -->
<!--                        tuneGrid = svmGrid, -->
<!--                        metric = "Accmax", -->
<!--                        trControl = fitControl) -->

<!-- models <- c("LogitBoost", 'svmRadial', 'rf', 'pls', 'xgbTree') -->
<!-- for (i in 1:5) { -->
<!--   if (i == 2) set.seed(45) -->
<!--   else set.seed(830) -->
<!--   xgb.fit <- train(Health_State~., method=models[i], data=data, metric = "Accmax", -->
<!--                    trControl = fitControl, tuneGrid = mat.all[[i]]$bestTune) -->

<!--   xgb.fit$bestTune -->

<!--   r <- roc(xgb.fit$pred$obs, xgb.fit$pred$pos) -->
<!--   thresh <- coords(r, "best", ret = "threshold") -->
<!--   pred.loocv <- ifelse(xgb.fit$pred$pos >= thresh, "pos", "neg") -->

<!--   all.acc[i+1, 1] <- mean(pred.loocv == xgb.fit$pred$obs) -->

<!--   set.seed(830) -->
<!--   probs.test <- predict.train(xgb.fit, data.test, type = "prob") -->
<!--   pred.test <- ifelse(probs.test$pos > thresh, "pos", "neg") -->

<!--   all.acc[i+1, 2] <- mean(pred.test == data.test$Health_State) -->
<!-- }  -->

<!-- all.acc %>%  kable() %>%  kable_styling() -->
<!-- ``` -->

<!-- ## Significant metabolites -->

<!-- ### Lasso -->

<!-- ```{r, cache=T} -->
<!-- sig.acc <- matrix(nrow = 6, ncol = 2) -->
<!-- colnames(sig.acc) <- c("LOOCV", "External") -->
<!-- rownames(sig.acc) <- c("Lasso", "Logit Boost", "SVM", "RF", "PLS", "xgbTree") -->

<!-- plasma.met.idx <- plasma.met.idx[-c(1, 2, 7, 12)] -->

<!-- health_df_plasma_full <- health_df_plasma_full[, c(1, plasma.met.idx - 3)] -->
<!-- health_df_plasma_full.test <- health_df_plasma_full.test[, c(1, plasma.met.idx - 3)] -->
<!-- # cml.clus.plasma <- ModelTrain(health_df_plasma_full) -->
<!-- # CombineSplits(cml.clus.plasma, metric = "error rate") -->

<!-- cor.cols <- findCorrelation(cor(data.matrix(health_df_plasma_full)), cutoff = .9) -->
<!-- cor.cols -->

<!-- x = model.matrix(Health_State ~ ., data = health_df_plasma_full)[,-1] -->
<!-- y = health_df_plasma_full$Health_State -->
<!-- grid = 10^seq(10, -2, length = 100) -->

<!-- lasso.mod <- glmnet(x, y, family = "binomial", alpha = 1, lambda = grid) -->
<!-- plot(lasso.mod) -->

<!-- set.seed(835) -->
<!-- cv.out = cv.glmnet(x, y, family="binomial", alpha = 1, type.measure="class", nfolds = 82) -->
<!-- bestlam = cv.out$lambda.min -->
<!-- bestlam -->

<!-- # LOOCV accuracy -->
<!-- sig.acc[1, 1] <- 1 - min(cv.out$cvm) -->

<!-- plot(cv.out) -->

<!-- cv.coef <- coef(cv.out, s = bestlam) -->
<!-- cv.coef <- as.matrix(Matrix(cv.coef, sparse = F)) -->
<!-- cv.coef[cv.coef != 0, ] -->

<!-- # prediction performance on test set -->

<!-- big.df.test.singles <- health_df_plasma_full.test -->

<!-- #remove correlated columns -->

<!-- # big.df.test.singles <- big.df.test.singles[, -cor.cols] -->
<!-- x.test = model.matrix(Health_State ~ ., data = big.df.test.singles)[, -1] -->
<!-- y.test = big.df.test.singles$Health_State -->
<!-- lasso.pred <- predict(lasso.mod, s = bestlam, newx = x.test, type = "class") -->
<!-- lasso.pred <- as.numeric(lasso.pred[, 1]) -->

<!-- # test accuracy -->
<!-- sig.acc[1, 2] <- mean(lasso.pred == y.test) -->
<!-- mean(lasso.pred == y.test) -->

<!-- # specificity.test -->
<!-- idx <- y.test == 0 -->
<!-- mean(y.test[idx] == lasso.pred[idx]) -->

<!-- # sensitivity.test -->
<!-- idx <- y.test == 1 -->
<!-- mean(y.test[idx] == lasso.pred[idx]) -->

<!-- head(health_df_plasma_full) -->
<!-- dim(health_df_plasma_full) -->
<!-- ``` -->

<!-- ### Other ML -->

<!-- ```{r} -->
<!-- data <- health_df_plasma_full -->
<!-- data$Health_State <- as.factor(ifelse(data$Health_State == 0, "neg", "pos")) -->

<!-- data.test <- big.df.test.singles -->
<!-- data.test$Health_State <- as.factor(ifelse(data.test$Health_State == 0, "neg", "pos")) -->
<!-- ``` -->

<!-- ```{r, cache = T} -->
<!-- mat = lapply(c("LogitBoost", 'svmRadial', 'rf', 'pls', 'xgbTree'),  -->
<!--              function (met) { -->
<!--                set.seed(830) -->
<!--                train(Health_State~., method=met, data=data, tuneLength = 10, metric = "Accmax", -->
<!--                      trControl = fitControl) -->
<!--              }) -->
<!-- mat.sig <- mat -->
<!-- ``` -->

<!-- ```{r, cache = T} -->
<!-- svmGrid <- expand.grid(sigma= 2^c(-25, -20, -15,-10, -5, 0), -->
<!--                        C= 2^c(0:5)) -->
<!-- set.seed(45)  -->
<!-- mat.sig[[2]] <- train(Health_State~., data = data,  -->
<!--                        method = "svmRadial", -->
<!--                        tuneGrid = svmGrid, -->
<!--                        metric = "Accmax", -->
<!--                        trControl = fitControl) -->

<!-- models <- c("LogitBoost", 'svmRadial', 'rf', 'pls', 'xgbTree') -->
<!-- for (i in 1:5) { -->
<!--   if (i == 2) set.seed(45) -->
<!--   else set.seed(830) -->
<!--   xgb.fit <- train(Health_State~., method=models[i], data=data, metric = "Accmax", -->
<!--                    trControl = fitControl, tuneGrid = mat.sig[[i]]$bestTune) -->

<!--   xgb.fit$bestTune -->

<!--   r <- roc(xgb.fit$pred$obs, xgb.fit$pred$pos) -->
<!--   thresh <- coords(r, "best", ret = "threshold") -->
<!--   pred.loocv <- ifelse(xgb.fit$pred$pos >= thresh, "pos", "neg") -->

<!--   sig.acc[i+1, 1] <- mean(pred.loocv == xgb.fit$pred$obs) -->

<!--   set.seed(830) -->
<!--   probs.test <- predict.train(xgb.fit, data.test, type = "prob") -->
<!--   pred.test <- ifelse(probs.test$pos > thresh, "pos", "neg") -->

<!--   sig.acc[i+1, 2] <- mean(pred.test == data.test$Health_State) -->
<!-- }  -->

<!-- sig.acc %>%  kable() %>%  kable_styling() -->
<!-- ``` -->

<!-- ## Cluster metabolites -->

<!-- ### Lasso -->

<!-- ```{r, cache=T} -->
<!-- clus.acc <- matrix(nrow = 6, ncol = 2) -->
<!-- colnames(clus.acc) <- c("LOOCV", "External") -->
<!-- rownames(clus.acc) <- c("Lasso", "Logit Boost", "SVM", "RF", "PLS", "xgbTree") -->

<!-- health_df_plasma_full <- health_df_plasma_full[, c(1, 2, 3, 4)] -->
<!-- health_df_plasma_full.test <- health_df_plasma_full.test[, c(1, 2, 3, 4)] -->
<!-- # cml.clus.plasma <- ModelTrain(health_df_plasma_full) -->
<!-- # CombineSplits(cml.clus.plasma, metric = "error rate") -->

<!-- cor.cols <- findCorrelation(cor(data.matrix(health_df_plasma_full)), cutoff = .9) -->
<!-- cor.cols -->

<!-- x = model.matrix(Health_State ~ ., data = health_df_plasma_full)[,-1] -->
<!-- y = health_df_plasma_full$Health_State -->
<!-- grid = 10^seq(10, -2, length = 100) -->

<!-- lasso.mod <- glmnet(x, y, family = "binomial", alpha = 1, lambda = grid) -->
<!-- plot(lasso.mod) -->

<!-- set.seed(835) -->
<!-- cv.out = cv.glmnet(x, y, family="binomial", alpha = 1, type.measure="class", nfolds = 82) -->
<!-- bestlam = cv.out$lambda.min -->
<!-- bestlam -->

<!-- # LOOCV accuracy -->
<!-- clus.acc[1, 1] <- 1 - min(cv.out$cvm) -->

<!-- plot(cv.out) -->

<!-- cv.coef <- coef(cv.out, s = bestlam) -->
<!-- cv.coef <- as.matrix(Matrix(cv.coef, sparse = F)) -->
<!-- cv.coef[cv.coef != 0, ] -->

<!-- # prediction performance on test set -->

<!-- big.df.test.singles <- health_df_plasma_full.test -->

<!-- #remove correlated columns -->

<!-- # big.df.test.singles <- big.df.test.singles[, -cor.cols] -->
<!-- x.test = model.matrix(Health_State ~ ., data = big.df.test.singles)[, -1] -->
<!-- y.test = big.df.test.singles$Health_State -->
<!-- lasso.pred <- predict(lasso.mod, s = bestlam, newx = x.test, type = "class") -->
<!-- lasso.pred <- as.numeric(lasso.pred[, 1]) -->

<!-- # test accuracy -->
<!-- clus.acc[1, 2] <- mean(lasso.pred == y.test) -->

<!-- # specificity.test -->
<!-- idx <- y.test == 0 -->
<!-- mean(y.test[idx] == lasso.pred[idx]) -->

<!-- # sensitivity.test -->
<!-- idx <- y.test == 1 -->
<!-- mean(y.test[idx] == lasso.pred[idx]) -->
<!-- ``` -->

<!-- ### Other ML -->

<!-- ```{r} -->
<!-- data <- health_df_plasma_full -->
<!-- data$Health_State <- as.factor(ifelse(data$Health_State == 0, "neg", "pos")) -->

<!-- data.test <- big.df.test.singles -->
<!-- data.test$Health_State <- as.factor(ifelse(data.test$Health_State == 0, "neg", "pos")) -->
<!-- ``` -->

<!-- ```{r, cache = T} -->
<!-- mat = lapply(c("LogitBoost", 'svmRadial', 'rf', 'pls', 'xgbTree'),  -->
<!--              function (met) { -->
<!--                set.seed(830) -->
<!--                train(Health_State~., method=met, data=data, tuneLength = 10, metric = "Accmax", -->
<!--                      trControl = fitControl) -->
<!--              }) -->
<!-- mat.clus <- mat -->
<!-- ``` -->

<!-- ```{r, cache = T} -->
<!-- svmGrid <- expand.grid(sigma= 2^c(-25, -20, -15,-10, -5, 0), -->
<!--                        C= 2^c(0:5)) -->
<!-- set.seed(830)  -->
<!-- mat.clus[[2]] <- train(Health_State~., data = data,  -->
<!--                        method = "svmRadial", -->
<!--                        tuneGrid = svmGrid, -->
<!--                        metric = "Accmax", -->
<!--                        trControl = fitControl) -->

<!-- models <- c("LogitBoost", 'svmRadial', 'rf', 'pls', 'xgbTree') -->
<!-- for (i in 1:5) { -->
<!--   # if (i == 2) set.seed(45) -->
<!--   # else set.seed(830) -->
<!--   xgb.fit <- train(Health_State~., method=models[i], data=data, metric = "Accmax", -->
<!--                    trControl = fitControl, tuneGrid = mat.clus[[i]]$bestTune) -->

<!--   xgb.fit$bestTune -->

<!--   r <- roc(xgb.fit$pred$obs, xgb.fit$pred$pos) -->
<!--   thresh <- coords(r, "best", ret = "threshold") -->
<!--   pred.loocv <- ifelse(xgb.fit$pred$pos >= thresh, "pos", "neg") -->

<!--   clus.acc[i+1, 1] <- mean(pred.loocv == xgb.fit$pred$obs) -->

<!--   set.seed(830) -->
<!--   probs.test <- predict.train(xgb.fit, data.test, type = "prob") -->
<!--   pred.test <- ifelse(probs.test$pos > thresh, "pos", "neg") -->

<!--   clus.acc[i+1, 2] <- mean(pred.test == data.test$Health_State) -->
<!-- }  -->

<!-- clus.acc %>%  kable() %>%  kable_styling() -->
<!-- ``` -->

